version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: True
      MYSQL_DATABASE: flask_app
    ports:
      - "3307:3306"
    networks:
      - flask_app
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  flask:
    depends_on:
      - db
    build: ./Docker
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "./:/app"
    networks:
      - flask_app
networks:
  flask_app:
